'use client'
import{useCallback,useEffect,useMemo,useState}from'react';import Sidebar from '@/components/Sidebar';import{supabase}from'@/lib/supabase';import{AlertTriangle,CheckCircle2,FileText,Loader2,RefreshCw,Search,X}from'lucide-react'
type Pedido={id:string;numero:number;nombre_cliente:string;email_cliente:string|null;telefono:string;total:number;created_at:string}
type Factura={id:string;pedido_id:string;estado:string;numero_factura:string|null;clave_acceso:string|null;fecha_emision:string|null;total:number|null;ride_url:string|null;xml_url:string|null;observaciones:string|null}
const money=(n:number)=>new Intl.NumberFormat('es-EC',{style:'currency',currency:'USD'}).format(n||0)
export default function FacturacionPage(){const[pedidos,setPedidos]=useState<Pedido[]>([]),[facturas,setFacturas]=useState<Factura[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[tab,setTab]=useState<'pendiente'|'emitida'>('pendiente'),[q,setQ]=useState(''),[modal,setModal]=useState<Pedido|null>(null),[numero,setNumero]=useState(''),[clave,setClave]=useState(''),[obs,setObs]=useState(''),[saving,setSaving]=useState(false)
const cargar=useCallback(async()=>{setLoading(true);setError('');const sync=await supabase.rpc('sincronizar_facturas_pendientes');if(sync.error){setError(sync.error.message);setLoading(false);return}const[f,e]=await Promise.all([supabase.from('rep_facturas_cliente').select('*').order('created_at',{ascending:false}),supabase.from('rep_entregas').select('pedido_id').eq('exitosa',true)]);if(f.error){setError(f.error.message);setLoading(false);return}const ids=[...new Set((e.data||[]).map(x=>x.pedido_id))];const p=ids.length?await supabase.from('ol_pedidos').select('id,numero,nombre_cliente,email_cliente,telefono,total,created_at').in('id',ids).order('numero',{ascending:false}):{data:[],error:null};setFacturas((f.data||[])as Factura[]);setPedidos((p.data||[])as Pedido[]);setLoading(false)},[]);useEffect(()=>{const t=setTimeout(()=>void cargar(),0);return()=>clearTimeout(t)},[cargar])
const fMap=useMemo(()=>new Map(facturas.map(f=>[f.pedido_id,f])),[facturas]);const list=pedidos.filter(p=>(tab==='emitida'?fMap.get(p.id)?.estado==='emitida':fMap.get(p.id)?.estado!=='emitida')&&(!q||`${p.numero} ${p.nombre_cliente} ${p.email_cliente}`.toLowerCase().includes(q.toLowerCase())))
function abrir(p:Pedido){setModal(p);setNumero('');setClave('');setObs('')}
async function guardar(){if(!modal||!numero.trim())return;setSaving(true);const{error}=await supabase.rpc('registrar_factura_cliente',{p_pedido_id:modal.id,p_numero:numero.trim(),p_clave:clave.trim()||null,p_ride_url:null,p_xml_url:null,p_observaciones:obs.trim()||null});setSaving(false);if(error){setError(error.message);return}setModal(null);await cargar()}
return <div className="flex min-h-screen bg-slate-100"><Sidebar/><main className="flex-1 space-y-5 p-4 pt-16 md:ml-56 md:p-6"><header className="flex items-end justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-green-600">Ventas</p><h1 className="text-2xl font-black">Facturación al cliente</h1><p className="text-sm text-slate-500">Pedidos entregados que deben facturarse. No confundir con la factura de compra del shopper.</p></div><button onClick={cargar} className="rounded-xl border bg-white p-2.5"><RefreshCw size={16} className={loading?'animate-spin':''}/></button></header>
<div className="flex gap-2 rounded-xl border border-blue-200 bg-blue-50 p-3 text-xs text-blue-800"><FileText size={16}/><span><b>Flujo correcto:</b> el shopper registra la factura del proveedor a nombre de La Crayola; esta pantalla registra la factura de venta al cliente después de la entrega.</span></div>
{error&&<div className="flex gap-2 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700"><AlertTriangle size={17}/>{error.includes('does not exist')?'Ejecuta migration_facturacion_doble_flujo.sql en Supabase.':error}</div>}
<section className="rounded-2xl border bg-white shadow-sm"><div className="flex flex-wrap gap-2 border-b p-4"><button onClick={()=>setTab('pendiente')} className={`rounded-xl px-4 py-2 text-xs font-bold ${tab==='pendiente'?'bg-orange-500 text-white':'bg-slate-100'}`}>Pendientes ({pedidos.filter(p=>fMap.get(p.id)?.estado!=='emitida').length})</button><button onClick={()=>setTab('emitida')} className={`rounded-xl px-4 py-2 text-xs font-bold ${tab==='emitida'?'bg-green-600 text-white':'bg-slate-100'}`}>Emitidas ({pedidos.filter(p=>fMap.get(p.id)?.estado==='emitida').length})</button><div className="relative ml-auto"><Search className="absolute left-3 top-2.5 text-slate-400" size={14}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar pedido o cliente" className="rounded-xl border py-2 pl-9 pr-3 text-sm"/></div></div>{loading?<div className="flex justify-center p-16"><Loader2 className="animate-spin"/></div>:<div className="divide-y">{list.map(p=>{const f=fMap.get(p.id);return <div key={p.id} className="flex flex-wrap items-center gap-3 p-4"><div className={`flex h-10 w-10 items-center justify-center rounded-xl ${f?.estado==='emitida'?'bg-green-50 text-green-600':'bg-orange-50 text-orange-600'}`}>{f?.estado==='emitida'?<CheckCircle2 size={18}/>:<FileText size={18}/>}</div><div className="min-w-0 flex-1"><p className="font-black">#{String(p.numero).padStart(4,'0')} · {p.nombre_cliente}</p><p className="text-xs text-slate-500">{p.email_cliente||p.telefono} · Entrega confirmada</p>{f?.numero_factura&&<p className="text-[10px] font-bold text-green-700">Factura {f.numero_factura}{f.clave_acceso?` · Clave ${f.clave_acceso}`:''}</p>}</div><p className="font-black">{money(p.total)}</p>{f?.estado!=='emitida'&&<button onClick={()=>abrir(p)} className="rounded-xl bg-green-600 px-4 py-2.5 text-xs font-bold text-white">Registrar factura emitida</button>}</div>})}{!list.length&&<p className="p-16 text-center text-sm text-slate-400">No hay pedidos en este estado.</p>}</div>}</section>
{modal&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-5 shadow-2xl"><div className="flex justify-between"><div><h2 className="font-black">Registrar factura de venta</h2><p className="text-xs text-slate-500">Pedido #{modal.numero} · {modal.nombre_cliente}</p></div><button onClick={()=>setModal(null)}><X size={18}/></button></div><div className="mt-5 space-y-3"><label className="block text-xs font-bold text-slate-600">Número de factura *<input value={numero} onChange={e=>setNumero(e.target.value)} placeholder="001-001-000000123" className="mt-1 w-full rounded-xl border px-3 py-2.5 text-sm"/></label><label className="block text-xs font-bold text-slate-600">Clave de acceso SRI<input value={clave} onChange={e=>setClave(e.target.value)} placeholder="Clave real, si está disponible" className="mt-1 w-full rounded-xl border px-3 py-2.5 text-sm"/></label><label className="block text-xs font-bold text-slate-600">Observaciones<textarea value={obs} onChange={e=>setObs(e.target.value)} rows={3} className="mt-1 w-full rounded-xl border px-3 py-2.5 text-sm"/></label><p className="rounded-xl bg-amber-50 p-3 text-[10px] text-amber-800">Este registro no autoriza documentos ante el SRI. Debes ingresar datos de una factura realmente emitida por el sistema autorizado.</p></div><div className="mt-5 flex gap-2"><button onClick={()=>setModal(null)} className="flex-1 rounded-xl bg-slate-100 py-2.5 text-xs font-bold">Cancelar</button><button onClick={guardar} disabled={!numero.trim()||saving} className="flex-1 rounded-xl bg-green-600 py-2.5 text-xs font-bold text-white disabled:opacity-50">{saving?'Guardando…':'Confirmar emisión'}</button></div></div></div>}</main></div>}
