'use client'

import { useCallback, useEffect, useMemo, useState } from 'react'
import Sidebar from '@/components/Sidebar'
import { supabase } from '@/lib/supabase'
import { AlertTriangle, Bike, CheckCircle2, Clock3, Download, Loader2, Package, RefreshCw, ShoppingBasket, TrendingUp, XCircle } from 'lucide-react'

const fmt = (n:number) => new Intl.NumberFormat('es-EC',{style:'currency',currency:'USD'}).format(n||0)
const dateInput = (offset=0) => { const d=new Date(); d.setDate(d.getDate()+offset); return d.toISOString().slice(0,10) }
const csvCell = (v: unknown) => `"${String(v ?? '').replaceAll('"','""')}"`
type Persona = { nombre?: string } | null
type Asig = { id:string; pedido_id:string; estado:string; asignado_at:string; updated_at?:string; shopper_id?:string|null; rider_id?:string|null; repartidor_id?:string|null; shopper?:Persona; rider?:Persona; repartidor?:Persona }
type Entrega = { pedido_id:string; repartidor_id:string; monto_cobrado:number; exitosa:boolean; entregado_at:string; salida_at?:string|null; tiempo_entrega?:number|null; motivo_fallo?:string|null; repartidor?:Persona }
type Pedido = { id:string; numero:number; estado:string; total:number; costo_envio?:number|null; total_final?:number|null; created_at:string; nombre_cliente:string }

export default function ReportesPage(){
  const [desde,setDesde]=useState(dateInput(-30)); const [hasta,setHasta]=useState(dateInput())
  const [pedidos,setPedidos]=useState<Pedido[]>([]); const [asigs,setAsigs]=useState<Asig[]>([]); const [entregas,setEntregas]=useState<Entrega[]>([])
  const [loading,setLoading]=useState(true); const [error,setError]=useState('')
  const cargar=useCallback(async()=>{setLoading(true);setError('');const fin=`${hasta}T23:59:59.999Z`;const inicio=`${desde}T00:00:00.000Z`
    const [p,a,e]=await Promise.all([
      supabase.from('ol_pedidos').select('id,numero,estado,total,costo_envio,total_final,created_at,nombre_cliente').gte('created_at',inicio).lte('created_at',fin).order('created_at',{ascending:false}),
      supabase.from('rep_asignaciones').select('id,pedido_id,estado,asignado_at,updated_at,shopper_id,rider_id,repartidor_id,shopper:rep_repartidores!rep_asignaciones_shopper_id_fkey(nombre),rider:rep_repartidores!rep_asignaciones_rider_id_fkey(nombre),repartidor:rep_repartidores!rep_asignaciones_repartidor_id_fkey(nombre)').gte('asignado_at',inicio).lte('asignado_at',fin),
      supabase.from('rep_entregas').select('pedido_id,repartidor_id,monto_cobrado,exitosa,entregado_at,salida_at,tiempo_entrega,motivo_fallo,repartidor:rep_repartidores(nombre)').gte('entregado_at',inicio).lte('entregado_at',fin),
    ]);const err=p.error||a.error||e.error;if(err)setError(err.message);setPedidos((p.data??[]) as Pedido[]);setAsigs((a.data??[]) as unknown as Asig[]);setEntregas((e.data??[]) as unknown as Entrega[]);setLoading(false)},[desde,hasta])
  useEffect(()=>{const timer=window.setTimeout(()=>void cargar(),0);return()=>window.clearTimeout(timer)},[cargar])

  // M4 de la auditoria financiera: esto se llamaba "Facturado" pero nunca
  // sumo facturas reales (rep_facturas_cliente), solo el total de pedidos
  // entregados, y encima sin el envio. Se renombra a lo que realmente es,
  // y se suma total_final (con envio) cuando esta disponible.
  const stats=useMemo(()=>{const exitosas=entregas.filter(e=>e.exitosa);const fallidas=entregas.filter(e=>!e.exitosa);const entregadosIds=new Set(exitosas.map(e=>e.pedido_id));const ventasEntregadas=pedidos.filter(p=>entregadosIds.has(p.id)||p.estado==='entregado').reduce((s,p)=>s+Number(p.total_final??((p.total||0)+(p.costo_envio||0))),0);const tiempos=exitosas.map(e=>Number(e.tiempo_entrega||(e.salida_at?(new Date(e.entregado_at).getTime()-new Date(e.salida_at).getTime())/60000:0))).filter(t=>t>0&&t<=1440);const avg=tiempos.length?Math.round(tiempos.reduce((s,t)=>s+t,0)/tiempos.length):0
    const riders=new Map<string,{nombre:string;entregas:number;fallidas:number;cobrado:number;minutos:number}>();entregas.forEach(e=>{const key=e.repartidor_id;const x=riders.get(key)??{nombre:e.repartidor?.nombre||'Sin nombre',entregas:0,fallidas:0,cobrado:0,minutos:0};if(e.exitosa){x.entregas++;x.cobrado+=Number(e.monto_cobrado||0);x.minutos+=Number(e.tiempo_entrega||0)}else x.fallidas++;riders.set(key,x)})
    const shoppers=new Map<string,{nombre:string;asignados:number;completados:number;devueltos:number}>();asigs.forEach(a=>{const key=a.shopper_id||a.repartidor_id;if(!key)return;const x=shoppers.get(key)??{nombre:a.shopper?.nombre||a.repartidor?.nombre||'Sin nombre',asignados:0,completados:0,devueltos:0};x.asignados++;if(['recolectado','en_ruta','entregado'].includes(a.estado))x.completados++;if(['devuelto','cancelado'].includes(a.estado))x.devueltos++;shoppers.set(key,x)})
    return {exitosas,fallidas,ventasEntregadas,avg,anomalias:exitosas.filter(e=>e.monto_cobrado==null||(e.salida_at&&new Date(e.salida_at)>new Date(e.entregado_at))).length,tasa:entregas.length?exitosas.length/entregas.length*100:0,cancelados:pedidos.filter(p=>p.estado==='cancelado').length,riders:[...riders.values()].sort((a,b)=>b.entregas-a.entregas),shoppers:[...shoppers.values()].sort((a,b)=>b.completados-a.completados)}},[pedidos,asigs,entregas])

  function exportar(){const rows=[['Tipo','Nombre','Asignados/Entregas','Completados/Fallidas','Efectividad','Monto cobrado'],...stats.riders.map(r=>['Repartidor',r.nombre,r.entregas,r.fallidas,`${r.entregas+r.fallidas?Math.round(r.entregas/(r.entregas+r.fallidas)*100):0}%`,r.cobrado]),...stats.shoppers.map(s=>['Comprador',s.nombre,s.asignados,s.completados,`${s.asignados?Math.round(s.completados/s.asignados*100):0}%`,''])];const blob=new Blob(['\ufeff'+rows.map(row=>row.map(csvCell).join(',')).join('\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`analitica-${desde}-${hasta}.csv`;a.click();URL.revokeObjectURL(url)}
  const cards=[
    {label:'Pedidos',value:pedidos.length,icon:Package,tone:'text-blue-600 bg-blue-50'},
    {label:'Entregas',value:stats.exitosas.length,icon:CheckCircle2,tone:'text-green-600 bg-green-50'},
    {label:'Ventas entregadas',value:fmt(stats.ventasEntregadas),icon:TrendingUp,tone:'text-emerald-600 bg-emerald-50'},
    {label:'Efectividad',value:`${stats.tasa.toFixed(1)}%`,icon:Bike,tone:'text-violet-600 bg-violet-50'},
    {label:'Tiempo promedio',value:stats.avg?`${stats.avg} min`:'—',icon:Clock3,tone:'text-orange-600 bg-orange-50'},
    {label:'Cancelados',value:stats.cancelados,icon:XCircle,tone:'text-red-600 bg-red-50'},
  ]

  return <div className="flex min-h-screen bg-slate-100"><Sidebar/><main className="flex-1 space-y-5 p-4 pt-16 md:ml-56 md:p-6">
    <header className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.18em] text-green-600">Analítica</p><h1 className="text-2xl font-black text-slate-900">Rendimiento operativo</h1><p className="text-sm text-slate-500">Métricas calculadas desde asignaciones y entregas reales.</p></div><div className="flex flex-wrap items-center gap-2"><input type="date" value={desde} onChange={e=>setDesde(e.target.value)} className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm"/><span className="text-xs text-slate-400">a</span><input type="date" value={hasta} onChange={e=>setHasta(e.target.value)} className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm"/><button onClick={cargar} className="rounded-xl border border-slate-200 bg-white p-2.5" title="Actualizar"><RefreshCw size={16} className={loading?'animate-spin':''}/></button><button onClick={exportar} className="flex items-center gap-2 rounded-xl bg-slate-900 px-3 py-2.5 text-xs font-bold text-white"><Download size={15}/> CSV</button></div></header>
    {error&&<div className="flex gap-2 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700"><AlertTriangle size={18}/>{error}</div>}
    {stats.anomalias>0&&<div className="flex gap-2 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800"><AlertTriangle size={18}/><span>{stats.anomalias} entrega(s) presentan monto vacío o fechas invertidas. Los tiempos inválidos no participan en el promedio.</span></div>}
    <section className="grid grid-cols-2 gap-3 lg:grid-cols-6">{cards.map(({label,value,icon:Icon,tone})=><div key={label} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className={`mb-3 flex h-9 w-9 items-center justify-center rounded-xl ${tone}`}><Icon size={17}/></div><p className="text-xl font-black text-slate-900">{loading?<Loader2 size={18} className="animate-spin"/>:value}</p><p className="text-xs text-slate-500">{label}</p></div>)}</section>
    <section className="grid gap-4 xl:grid-cols-2"><Ranking title="Repartidores" subtitle="Entrega, recaudo y efectividad" icon={Bike} columns={['Entregas','Éxito','Cobrado']} rows={stats.riders.map(r=>({name:r.nombre,values:[r.entregas,`${r.entregas+r.fallidas?Math.round(r.entregas/(r.entregas+r.fallidas)*100):0}%`,fmt(r.cobrado)]}))}/><Ranking title="Compradores / shoppers" subtitle="Carga tomada y pedidos completados" icon={ShoppingBasket} columns={['Asignados','Completados','Éxito']} rows={stats.shoppers.map(s=>({name:s.nombre,values:[s.asignados,s.completados,`${s.asignados?Math.round(s.completados/s.asignados*100):0}%`]}))}/></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-black text-slate-900">Embudo del pedido</h2><p className="mb-5 text-xs text-slate-500">Distribución de estados en el período seleccionado.</p><div className="space-y-3">{Object.entries(pedidos.reduce<Record<string,number>>((m,p)=>(m[p.estado]=(m[p.estado]||0)+1,m),{})).sort((a,b)=>b[1]-a[1]).map(([estado,count])=><div key={estado}><div className="mb-1 flex justify-between text-xs"><span className="font-bold capitalize text-slate-600">{estado.replaceAll('_',' ')}</span><span className="font-black">{count}</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-green-500" style={{width:`${pedidos.length?count/pedidos.length*100:0}%`}}/></div></div>)}</div></section>
  </main></div>
}

function Ranking({title,subtitle,icon:Icon,columns,rows}:{title:string;subtitle:string;icon:typeof Bike;columns:string[];rows:{name:string;values:(string|number)[]}[]}){return <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center gap-3 border-b border-slate-100 p-5"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-green-50 text-green-600"><Icon size={18}/></div><div><h2 className="font-black text-slate-900">{title}</h2><p className="text-xs text-slate-500">{subtitle}</p></div></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-[10px] uppercase tracking-wide text-slate-400"><tr><th className="px-5 py-3">Nombre</th>{columns.map(c=><th key={c} className="px-3 py-3 text-right">{c}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{rows.map((r,i)=><tr key={`${r.name}-${i}`}><td className="px-5 py-3 font-bold text-slate-800"><span className="mr-2 text-xs text-slate-300">{i+1}</span>{r.name}</td>{r.values.map((v,j)=><td key={j} className="px-3 py-3 text-right font-semibold text-slate-600">{v}</td>)}</tr>)}{!rows.length&&<tr><td colSpan={4} className="p-8 text-center text-sm text-slate-400">Sin actividad en este período.</td></tr>}</tbody></table></div></div>}
