'use client'
import {useCallback,useEffect,useMemo,useState} from 'react'
import Link from 'next/link';import Sidebar from '@/components/Sidebar';import {supabase} from '@/lib/supabase'
import {AlertTriangle,CheckCircle2,Clock3,CreditCard,FileText,Loader2,MapPin,PackageCheck,RefreshCw,Search,ShoppingCart,Truck,Users} from 'lucide-react'
type Row={id:string;numero:number;created_at:string;nombre_cliente:string;telefono:string;total:number;pedido_estado:string;metodo_pago:string|null;pago_confirmado:boolean|null;geo_lat:number|null;geo_lng:number|null;asignacion_id:string|null;asignacion_estado:string|null;shopper_nombre:string|null;rider_nombre:string|null;items_total:number;items_resueltos:number;items_faltantes:number;items_pendientes:number;comprobantes_proveedor:number;entrega_exitosa:boolean|null;entregado_at:string|null;monto_cobrado:number|null;entrega_foto:string|null;etapa_control:string;alertas:string[]}
const money=(n:number)=>new Intl.NumberFormat('es-EC',{style:'currency',currency:'USD'}).format(n||0)
const cfg:Record<string,{label:string;color:string}>={validar_pago:{label:'Validar pago',color:'bg-red-100 text-red-700'},confirmar_ubicacion:{label:'Confirmar ubicación',color:'bg-orange-100 text-orange-700'},asignar_comprador:{label:'Asignar comprador',color:'bg-amber-100 text-amber-700'},completar_compra:{label:'Completar compra',color:'bg-violet-100 text-violet-700'},revisar_faltantes:{label:'Revisar faltantes',color:'bg-red-100 text-red-700'},subir_comprobante_compra:{label:'Comprobante compra',color:'bg-pink-100 text-pink-700'},asignar_repartidor:{label:'Asignar repartidor',color:'bg-cyan-100 text-cyan-700'},seguir_entrega:{label:'Seguir entrega',color:'bg-blue-100 text-blue-700'},resolver_entrega_fallida:{label:'Entrega fallida',color:'bg-red-100 text-red-700'},facturar:{label:'Facturar',color:'bg-emerald-100 text-emerald-700'},completado:{label:'Completado',color:'bg-green-100 text-green-700'},en_proceso:{label:'En proceso',color:'bg-slate-100 text-slate-600'}}
export default function ControlPage(){const[rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[filtro,setFiltro]=useState('atencion'),[q,setQ]=useState('')
const cargar=useCallback(async()=>{setLoading(true);const{data,error}=await supabase.from('rep_control_pedidos_360').select('*').order('created_at',{ascending:false}).limit(300);setRows((data||[])as Row[]);setError(error?.message||'');setLoading(false)},[]);useEffect(()=>{const t=setTimeout(()=>void cargar(),0);return()=>clearTimeout(t)},[cargar])
const list=useMemo(()=>rows.filter(r=>(filtro==='todos'||(filtro==='atencion'&&r.alertas?.length)||(filtro==='compras'&&['completar_compra','revisar_faltantes','subir_comprobante_compra'].includes(r.etapa_control))||(filtro==='ruta'&&['asignar_repartidor','seguir_entrega','resolver_entrega_fallida'].includes(r.etapa_control))||(filtro==='facturar'&&r.etapa_control==='facturar'))&&(!q||`${r.numero} ${r.nombre_cliente} ${r.shopper_nombre} ${r.rider_nombre}`.toLowerCase().includes(q.toLowerCase()))),[rows,filtro,q])
const counts={alertas:rows.filter(r=>r.alertas?.length).length,pagos:rows.filter(r=>r.etapa_control==='validar_pago').length,ubicacion:rows.filter(r=>r.etapa_control==='confirmar_ubicacion').length,compras:rows.filter(r=>r.items_pendientes>0).length,ruta:rows.filter(r=>r.etapa_control==='seguir_entrega').length,facturar:rows.filter(r=>r.etapa_control==='facturar').length}
const cards=[{label:'Con alertas',value:counts.alertas,icon:AlertTriangle,tone:'text-red-600 bg-red-50'},{label:'Pagos',value:counts.pagos,icon:CreditCard,tone:'text-violet-600 bg-violet-50'},{label:'Sin GPS',value:counts.ubicacion,icon:MapPin,tone:'text-orange-600 bg-orange-50'},{label:'Compra pendiente',value:counts.compras,icon:ShoppingCart,tone:'text-amber-600 bg-amber-50'},{label:'En ruta',value:counts.ruta,icon:Truck,tone:'text-blue-600 bg-blue-50'},{label:'Por facturar',value:counts.facturar,icon:FileText,tone:'text-green-600 bg-green-50'}]
return <div className="flex min-h-screen bg-slate-100"><Sidebar/><main className="flex-1 space-y-5 p-4 pt-16 md:ml-56 md:p-6"><header className="flex items-end justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.18em] text-green-600">Operación</p><h1 className="text-2xl font-black">Control 360 de pedidos</h1><p className="text-sm text-slate-500">Pago → ubicación → compra → entrega → caja → factura.</p></div><button onClick={cargar} className="rounded-xl border bg-white p-2.5"><RefreshCw size={16} className={loading?'animate-spin':''}/></button></header>
{error&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error.includes('does not exist')?'Ejecuta migration_control_360.sql en Supabase.':error}</div>}
<section className="grid grid-cols-2 gap-3 lg:grid-cols-6">{cards.map(({label,value,icon:Icon,tone})=><div key={label} className="rounded-2xl border bg-white p-4 shadow-sm"><div className={`mb-2 flex h-8 w-8 items-center justify-center rounded-lg ${tone}`}><Icon size={16}/></div><p className="text-xl font-black">{value}</p><p className="text-xs text-slate-500">{label}</p></div>)}</section>
<section className="rounded-2xl border bg-white shadow-sm"><div className="flex flex-wrap gap-2 border-b p-4"><div className="relative mr-auto"><Search className="absolute left-3 top-2.5 text-slate-400" size={15}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Pedido, cliente o responsable" className="w-64 rounded-xl border py-2 pl-9 pr-3 text-sm"/></div>{[['atencion','Requiere atención'],['todos','Todos'],['compras','Compras'],['ruta','Entregas'],['facturar','Facturación']].map(([k,l])=><button key={k} onClick={()=>setFiltro(k)} className={`rounded-xl px-3 py-2 text-xs font-bold ${filtro===k?'bg-slate-900 text-white':'bg-slate-100 text-slate-600'}`}>{l}</button>)}</div>
{loading?<div className="flex justify-center p-16"><Loader2 className="animate-spin"/></div>:<div className="divide-y">{list.map(r=>{const c=cfg[r.etapa_control]||cfg.en_proceso;const action=r.etapa_control==='facturar'?'/asignaciones/facturacion':'/asignaciones';return <div key={r.id} className="p-4 hover:bg-slate-50"><div className="flex flex-wrap items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-slate-100"><PackageCheck size={17}/></div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><span className="font-black">#{String(r.numero).padStart(4,'0')}</span><span className="truncate text-sm text-slate-600">{r.nombre_cliente}</span><span className={`rounded-full px-2 py-1 text-[9px] font-bold ${c.color}`}>{c.label}</span></div><p className="text-[11px] text-slate-400">Comprador: {r.shopper_nombre||'Sin asignar'} · Rider: {r.rider_nombre||'Sin asignar'}</p></div><div className="text-right"><p className="font-black">{money(r.total)}</p><p className="text-[10px] text-slate-400">{r.items_resueltos}/{r.items_total} items</p></div><Link href={action} className="rounded-xl bg-green-600 px-3 py-2 text-xs font-bold text-white">Gestionar</Link></div><div className="mt-3 flex flex-wrap gap-2">{r.alertas?.map(a=><span key={a} className="rounded-lg bg-red-50 px-2 py-1 text-[10px] font-semibold text-red-700">{a}</span>)}{!r.alertas?.length&&<span className="flex items-center gap-1 text-[10px] font-bold text-green-600"><CheckCircle2 size={12}/> Sin alertas</span>}</div></div>})}{!list.length&&<p className="p-16 text-center text-sm text-slate-400">No hay pedidos para este filtro.</p>}</div>}</section></main></div>}
